apiVersion: v1
kind: Secret
metadata:
  name: tesla-bot-secrets
  namespace: tesla-app
type: Opaque
data:
  # Base64 encoded Refresh Token (from get_initial_token.py)
  # echo -n "YOUR_REFRESH_TOKEN" | base64
  refresh_token: ""
  
  # Base64 encoded Telegram Bot Token (from BotFather)
  # echo -n "YOUR_BOT_TOKEN" | base64
  telegram_token: ""
