apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tesla-tracker
  namespace: tesla-app
spec:
  serviceName: "tesla-tracker"
  replicas: 1
  selector:
    matchLabels:
      app: tesla-tracker
  template:
    metadata:
      labels:
        app: tesla-tracker
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      nodeSelector:
        kubernetes.io/hostname: k3s-ha-ovh-es
      tolerations:
      - key: "homelab"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      dnsPolicy: Default
      containers:
      - name: bot
        image: karasus15/tesla-tracker:latest
        imagePullPolicy: Always
        env:
        - name: TELEGRAM_TOKEN
          valueFrom:
            secretKeyRef:
              name: tesla-bot-secrets
              key: telegram_token
        volumeMounts:
        - mountPath: /data
          name: storage
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
      
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: tesla-pvc-local
